@Library("jenkins-shared-lib") _

pipeline {
    agent any

    parameters{
        string(name: "Num1", defaultValue: "10", description: "First number")
        string(name: "Num2", defaultValue: "5", description: "Second number")
        choice(name: "OPERATION",
            choices: ['add', 'subtract', 'multiply', 'divide'],
            description: 'Operation to perform on 2 numbers.')
    }
    
    stages{
        stage ('helloworld_function') {
            steps{
                helloWorld(name:"Maaz Patel", dayOfWeek:"Wednesday")
            }
        }
        stage ('calculator_function') {
            steps{
                script{
                    echo "Executing ${params.OPERATION} on numbers: ${params.Num1} and ${params.Num2}"
                    def NUM1 = params.Num1 as Integer
                    def NUM2 = params.Num2 as Integer
                    def OPS = ${params.OPERATION}

                    calculator(NUM1, NUM2, OPS)
                }
            }
        }
    }
}