@Library("jenkins-shared-lib") _

pipeline {
    parameters{
        string(name: "Num1")
        string(name: "Num2")
        choice(name: "OPERATION",
            choices: ['add', 'subtract', 'multiply', 'divide'],
            description: 'Operation to perform on 2 numbers.')
    }
    agent any
    stages{
        stage ('helloworld_function') {
            steps{
                helloWorld(name:"Maaz Patel", dayOfWeek:"Wednesday")
            }
        }
        stage ('calculator_function') {
            steps{
                echo "Executing ${params.OPERATION} on numbers: ${prams.Num1} and ${params.Num2}"
                NUM1 = ${prams.Num1}
                NUM2 = ${prams.Num2}
                OPS = ${params.OPERATION}
                calculator(NUM1, NUM2, OPS)
            }
        }
    }
}