@Library("jenkins-shared-lib") _
pipeline {
    agent any
    stages{
        stage ('helloworld_function') {
            steps{
                helloWorld(name:"Maaz Patel", dayOfWeek:"Wednesday")
            }
        }
    }
}